### PR TITLE
Cancel all messages in the queue

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
Or could it be bug that as root I cannot cancel all messages?

**Comment by szepeviktor** [comment]
Thank you!

**Comment by szepeviktor** [comment]
Do you have some comment on my question?

**Comment by svarshavchik** [comment]
There should not be any issues with root cancelling a message. It is possible that a given message cannot be cancelled if it's in the process of being delivered.

**Comment by szepeviktor** [comment]
Thank you!
Could you add a warning in that case?

**Comment by svarshavchik** [comment]
It's not as simple as it appears. mailq marks the message as cancelled, and sends a message to the daemon server to reload the queue. mailq has no knowledge of whether the message is in the process of being delivered. The daemon then figures out what the state of the message is, and if it can be cancelled immediately.

**Pull request merged**
